name: NPM Security Audit

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install  # Changed from npm ci to npm install
        
      - name: Run security audit (show details)
        run: npm audit
        continue-on-error: true
        
      - name: Generate package-lock.json
        run: npm install --package-lock-only
        
      - name: Upload package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
